# .github/workflows/release.yml
name: Build Desktop App (Python Backend + Tauri Frontend)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 安装 Python 依赖并执行 build.bat
      - name: Install Python dependencies & Build backend
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          backend\build.bat

      # 设置 Node 环境 + 安装前端依赖
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Enable Corepack + Install pnpm
        working-directory: BillNote_frontend
        run: |
          corepack enable
          pnpm install 

      # 设置 Rust 环境
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      # 打包 Tauri 应用
      - name: Build Tauri App
        working-directory: BillNote_frontend
        run: pnpm tauri build

      # 可选：上传构建产物
      - name: Upload Desktop Bundle
        uses: actions/upload-artifact@v4
        with:
          name: app-windows
          path: BillNote_frontend/src-tauri/target/release/bundle/
